import "./globals.css";
import Header from "./componnets/header";
import { Provider } from "react-redux";
import ReduxProvider from "./redux-provider";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Online exam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let userdata = null;

  if (typeof window !== "undefined") {
    userdata = localStorage.getItem("userdata");
  }

  console.log("userdata1111", userdata);
  return (
    <html lang="en">
      <body className={`${inter.className} app-shell`}>
        <main>
          <ReduxProvider>
            <Header />
            <div className="mx-auto w-full max-w-7xl px-4 pb-6 md:px-6">
              {children}
            </div>
            <ToastContainer />
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
